project_id = "yzydlthexjbtdmacqzey"

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.send-admin-message]
verify_jwt = true

[functions.send-push-notification]
verify_jwt = false

[functions.send-otp]
verify_jwt = false

[functions.verify-otp]
verify_jwt = false
